<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * AssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationRepository extends \Doctrine\ORM\EntityRepository
{
    function findass($no,$gouv)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select s from PIdevAllforkidsBundle:Association s 
    WHERE s.nom LIKE :no AND s.gouvernorat LIKE :gouv
      ")
            ->setParameter('no', '%' . $no . '%')->setParameter('gouv', '%' . $gouv . '%');
        return $query->getResult();
    }


public function NbrA()
{
    $query = $this->getEntityManager()
        ->createQuery(" 
    select COUNT (s) AS nb from PIdevAllforkidsBundle:Association s 
      ");
    return $query->getResult();

}
    public function associationActualitee()
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT g FROM PIdevAllforkidsBundle:Association g  ORDER BY g.id_aasociation DESC ");
        return $q->getFirstResult();
    }








}
