<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * CompteRPSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRPSRepository extends \Doctrine\ORM\EntityRepository
{

    public function TrouverCompte($Enfant)
    {


        $q=$this->getEntityManager()->createQuery("SELECT cmp FROM PIdevAllforkidsBundle:CompteRPS cmp WHERE cmp.enfant= :Enfant")
            ->setParameter('Enfant',$Enfant);
        return $q->getResult();
    }
}
