<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * EnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantRepository extends \Doctrine\ORM\EntityRepository
{

    public function CalculerNbrEnfant($Garderie)
    {

        $q = $this->getEntityManager()
            ->createQuery("SELECT COUNT (e) as nb FROM PIdevAllforkidsBundle:Enfant e WHERE e.garderie= :Garderie")
            ->setParameter('Garderie', $Garderie);
        return $q->getSingleScalarResult();

    }

    public function chercherEnfants($Garderie)
    {
        $q = $this->getEntityManager()
            ->createQuery("SELECT e FROM PIdevAllforkidsBundle:Enfant e WHERE e.garderie= :Garderie")
            ->setParameter('Garderie', $Garderie);
        return $q->getResult();


    }

    public function trouver($nom, $Garderie)
    {
        $q = $this->getEntityManager()
            ->createQuery("SELECT e FROM PIdevAllforkidsBundle:Enfant e JOIN PIdevAllforkidsBundle:Garderie g
WHERE e.garderie =:Garderie AND g.id_garderie=e.garderie
 AND e.nom LIKE :nom OR e.prenom LIKE :nom")->setParameter('nom', '%' . $nom . '%')->setParameter('Garderie', $Garderie);
        return $q->getResult();

    }

    public function trouver2($categorie, $Garderie)
    {


        $p = $this->getEntityManager()->createQuery("SELECT e FROM PIdevAllforkidsBundle:Enfant e JOIN PIdevAllforkidsBundle:Garderie g
WHERE e.categorie =:categorie AND e.garderie =:Garderie AND g.id_garderie=e.garderie")->setParameter('categorie', $categorie)
            ->setParameter('Garderie', $Garderie);
        return $p->getResult();
    }
}