<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * ExperiencePersonnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperiencePersonnelRepository extends \Doctrine\ORM\EntityRepository
{
}
