<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * GaleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleryRepository extends \Doctrine\ORM\EntityRepository
{
    public function chercher($Garderie)
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT l FROM PIdevAllforkidsBundle:Galery l JOIN PIdevAllforkidsBundle:Garderie g
 WHERE l.garderie= :Garderie AND g.id_garderie=l.garderie ")
            ->setParameter('Garderie',$Garderie);
        return $q->getArrayResult();



    }
}
