<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * GarderieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GarderieRepository extends \Doctrine\ORM\EntityRepository
{
//    public function trouver ($emplacement)
//    {
//
//        $q=$this->getEntityManager()
//            ->createQuery("SELECT g FROM PIdevAllforkidsBundle:Garderie g WHERE g.emplacement LIKE :emplacement ORDER BY g.capacite DESC ")->setParameter('emplacement',$emplacement.'%');
//        return $q->getResult();
//
//
//    }

    public function search($emp)
    {
//        die(var_dump($niveau));

        $query = $this->createQueryBuilder('g')
            ->select('g')
            ->where('g.emplacement LIKE :str')->orderBy('g.capacite');
        $query ->setParameter('str',  $emp.'%');
        return $query->getQuery()->getArrayResult();

    }
public function garderieActualitee()
{
    $q=$this->getEntityManager()
           ->createQuery("SELECT g FROM PIdevAllforkidsBundle:Garderie g  ORDER BY g.id_garderie DESC ");
        return $q->getFirstResult();
}


}
