<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * ListeAttRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeAttRepository extends \Doctrine\ORM\EntityRepository
{
    public function chercher($Garderie)
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT l FROM PIdevAllforkidsBundle:ListeAtt l JOIN PIdevAllforkidsBundle:Garderie g
 WHERE l.garderie= :Garderie AND g.id_garderie=l.garderie ORDER BY l.date")
            ->setParameter('Garderie',$Garderie);
        return $q->getArrayResult();



    }
    public function nbrEnfantListeAtt($Garderie)
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT COUNT (l) as nb FROM PIdevAllforkidsBundle:ListeAtt l JOIN PIdevAllforkidsBundle:Garderie g
 WHERE l.garderie= :Garderie AND g.id_garderie=l.garderie")
            ->setParameter('Garderie',$Garderie);
        return $q->getSingleScalarResult();

    }

    public function AncienEnfantDansListe($Garderie)
    {
        $p=$this->getEntityManager()->createQuery('SELECT l FROM PIdevAllforkidsBundle:ListeAtt l JOIN PIdevAllforkidsBundle:Garderie g WHERE  
 (l.garderie= :Garderie )AND (g.id_garderie=l.garderie) AND  (l.date< CURRENT_DATE ())')->setParameter('Garderie',$Garderie);
            return $p->getResult();


    }




}
