<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function mesNotifications($user, $lastLogin){
        $query = $this->getEntityManager()
            ->createQuery('SELECT n FROM PIdevAllforkidsBundle:Notification n WHERE n.destinataire = :us AND WHERE n.dateNotification > :da')
            ->setParameter('us', $user)
            ->setParameter('da', $lastLogin);
        $query->execute();
    }

    public function trieNotification(){
        $query = $this->getEntityManager()
            ->createQuery('SELECT n FROM PIdevAllforkidsBundle:Notification n ORDER BY n.dateNotification DESC ');
        return $query->getResult();
    }

}
