<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * OffreTransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreTransportRepository extends \Doctrine\ORM\EntityRepository
{

    public function rechercheOffre($destination){
        $query = $this->getEntityManager()
            ->createQuery('SELECT o FROM PIdevAllforkidsBundle:OffreTransport o WHERE o.destination LIKE :dest')
            ->setParameter('dest', '%'.$destination.'%');
        return $query->getResult();
    }


    public function offreActualitee()
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT g FROM PIdevAllforkidsBundle:OffreTransport g  ORDER BY g.id DESC ");
        return $q->getFirstResult();
    }



    public function searchOffre($des)
    {
//        die(var_dump($niveau));

        $query = $this->createQueryBuilder('o')
            ->select('o')
            ->where('o.destination LIKE :str')->orderBy('o.dateFin');
        $query ->setParameter('str',  $des.'%');
        return $query->getQuery()->getArrayResult();

    }

}
