<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPostByTitle($string){
        $query = $this->createQueryBuilder('d')
            ->select('d')
            ->where('d.titre LIKE :str')
            ->setParameter('str','%'.$string.'%');
            return $query ->getQuery()->getArrayResult();
    }

    public function findAllPostNoSignale(){

        $query=$this->createQueryBuilder('p')
            ->select('post')
            ->innerJoin("p.user","user")
            ->from('PIdevAllforkidsBundle:Post', 'post')
            ->where('p.nmbrsignal > 2');
        return $query ->getQuery()->getArrayResult();
    }


}
