<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * RatinggRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatinggRepository extends \Doctrine\ORM\EntityRepository
{


    public function chercher($Garderie)
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT l FROM PIdevAllforkidsBundle:Ratingg l JOIN PIdevAllforkidsBundle:Garderie g
 WHERE l.garderie= :Garderie AND g.id_garderie=l.garderie ")
            ->setParameter('Garderie',$Garderie);
        return $q->getArrayResult();



    }
    public function chercher2($Garderie)
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT l FROM PIdevAllforkidsBundle:Ratingg l JOIN PIdevAllforkidsBundle:Garderie g
 WHERE l.garderie= :Garderie AND g.id_garderie=l.garderie ")
            ->setParameter('Garderie',$Garderie);
        return $q->getFirstResult();



    }
}
