<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{

    public function NbrR($n)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select COUNT (s) AS nb from PIdevAllforkidsBundle:Reclamation s 
     WHERE s.etatRec LIKE :n 
      ")
            ->setParameter('n', '%' . $n . '%');
        return $query->getResult();

    }




    function findR($n)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select s from PIdevAllforkidsBundle:Reclamation s 
    WHERE s.etatRec LIKE :n 
      ")
            ->setParameter('n', '%' . $n . '%');
        return $query->getResult();
    }







}
