<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * ReservationTransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationTransportRepository extends \Doctrine\ORM\EntityRepository
{
    public function verifierReservation($user, $offre){
        $query = $this->getEntityManager()
            ->createQuery('SELECT o FROM PIdevAllforkidsBundle:ReservationTransport o WHERE o.user = :us AND o.offreTransport = :off')
            ->setParameter('us', $user)
            ->setParameter('off', $offre);
        $query->execute();

    }



}
