<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function membresEvenement($id)
    {

        $p=$this->getEntityManager()
            ->createQuery('select r from PIdevAllforkidsBundle:Reservation r where r.evenement=:id ORDER BY r.dateReservation' )->setParameter('id',$id);

        return $p->getResult();
    }
    public function reservation($usr,$id)
    {
        $query=$this->createQueryBuilder('m')
            ->where('m.evenement= :id' , 'm.user= :usr')->setParameter('id',$id)->setParameter('usr',$usr) ;
        return $query->getQuery()->getResult();
    }

    public function userReserv($usr,$id)
    {
        $p=$this->getEntityManager()
            ->createQuery('select r from PIdevAllforkidsBundle:Reservation r where r.user=:usr and r.evenement=:id' )->setParameter('usr',$usr)->setParameter('id',$id);

        return $p->getResult();
    }
    public function compteNbrReservation($id)
    {
        $query=$this->createQueryBuilder('m')->select('COUNT(m)')
            ->where('m.evenement= :id' )->setParameter('id',$id) ;
        return $query->getQuery()->getResult();
    }
}
