<?php

namespace PIdev\AllforkidsBundle\Repository;

/**
 * SignalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalRepository extends \Doctrine\ORM\EntityRepository
{


}
