<?php
/**
 * Created by PhpStorm.
 * User: Lauris
 * Date: 14/02/2018
 * Time: 22:22
 */

namespace PIdev\AllforkidsBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RechercheOffreTransportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('Destination');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

    public function getName()
    {
        return 'esprit_parcbundle_recherchemodele';
    }

}