security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ROLE_RESPONSABLE_GARDERIE: ROLE_RESPONSABLE_GARDERIE
        ROLE_ROLE_RESPONSABLE_CLUB: ROLE_RESPONSABLE_CLUB
        ROLE_ROLE_RESPONSABLE_ASSOCIATION: ROLE_RESPONSABLE_ASSOCIATION
        ROLE_USER:        ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login

            logout:
                            target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/home, role: ROLE_USER }
        - { path: ^/responsable_association, role: ROLE_RESPONSABLE_ASSOCIATION }
        - { path: ^/responsable_club, role: ROLE_RESPONSABLE_CLUB }